### ISSUE TITLE
Will the code be provided?

### ISSUE THREAD

**Issue by hamelsmu** [mynameisfiber/high_performance_python_2e#2]
Hi there.  Thanks for writing the book.  This is just a friendly question of whether or not the code for 2e will be available at some moment.  I noticed this repo contains many empty directories etc and appears to be scaffolding

**Comment by ianozsvald** [comment]
@hamelsmu huge apologies! The missing code is for my half of the book. I meant to upload it and then I became a new first-time father and now months have passed rapidly by! I do intend to get the code uploaded, I have to tidy it first and probably that won't happen this month (I have PyDataGlobal to prepare for, another public talk, and client engagements...and a baby) but I commit to making sure it is up in November. If there's something you were hoping to get your hands on quickly then say so and maybe I can push that bit up sooner?

**Comment by hamelsmu** [comment]
Totally understand.  I’ve since moved on to other things, however I just
wanted to let you know that I did miss the code :)

Congrats on being a new dad!!  I’m also one too 😀 it’s wonderful!  I hope
you can get to sleep soon I know how it is

**Comment by ianozsvald** [comment]
@hamelsmu all the code is online now, sorry again to be so slow (ps baby is now 5 months so life is slightly saner!). Cheers, Ian.
